#spring自动配置
spring:
  redis:
    host: localhost
    # 连接超时时间（记得添加单位，Duration）
    timeout: 10000ms
    # Redis默认情况下有16个分片，这里配置具体使用的分片
    # database: 0
    lettuce:
      pool:
        # 连接池最大连接数（使用负值表示没有限制） 默认 8
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        max-wait: -1ms
        # 连接池中的最大空闲连接 默认 8
        max-idle: 8
        # 连接池中的最小空闲连接 默认 0
        min-idle: 0
#    #集群配置
#    cluster:
#      nodes: 127.0.0.1:7001,127.0.0.1:7002,127.0.0.1:7003
#      max-redirects: 3
  cache:
    # 一般来说是不用配置的，Spring Cache 会根据依赖的包自行装配
    type: redis
logging:
  level:
    com.xkcoding: debug

#jedis配置
jedis:
  #单机standalone 集群(3.0及以上)cluster 3.0以下版本集群用shard
  model: standalone
  #单机host,port
  host: 10.247.100.14
  port: 9376
  #集群节点,用;分隔 maxAttempts
  instances: 192.168.220.128:7001;192.168.220.128:7000;192.168.220.128:7002;
  maxAttempts: 5
  password: test
  #连接超时时间ms
  timeout: 10000
  #连接池最大连接数（使用负值表示没有限制） 默认 8
  maxTotal: 100
  #连接池中的最大/最小空闲连接 默认 8/0
  maxIdle: 8
  minIdle: 0
  #连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
  maxWaitMillis: 20000
  #当调用borrow Object方法时，是否进行有效性检查，线上一般用false
  testOnBorrow: false
  #当调用return Object方法时，是否进行有效性检查，线上一般用false
  testOnReturn: false
  #idle object evitor线程对空闲连接扫描，若验证失败，会移除连接；这一项只有在timeBetweenEvictionRunsMillis大于0时才有意义；默认false
  testWhileIdle: true
  #表示idle object evitor两次扫描之间要sleep的毫秒数，逐出扫描的时间间隔（毫秒），为负不运行，默认为-1
  #作为验证连接是否有效的时间周期，如果testOnBorrow==false并且testWhileIdle==true,则在应用获取连接的时候会判断连接的空闲时间是否大于timeBetweenEvictionRunsMillis，如果大于则会验证该连接是否有效。
  timeBetweenEvictionRunsMillis: 60000
