server:
  port: 10010
  servlet:
    context-path: /demo
spring:
  datasource:
    url: jdbc:mysql://172.16.116.100:3307/dragnet_icall?useUnicode=true&characterEncoding=UTF-8&useSSL=false&autoReconnect=true&failOverReadOnly=false&serverTimezone=GMT%2B8
    username: icall_admin
    password: lS3OPeMdwELrJ
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      connection-test-query: SELECT 1 FROM DUAL
      maximum-pool-size: 20
      auto-commit: true
      idle-timeout: 30000
      pool-name: SpringBootDemoHikariCP
      max-lifetime: 60000
      connection-timeout: 30000

#freeswitch配置
##内联
freeswitch:
    inbound-host: 172.16.140.71
    inbound-port: 8021
    inbound-password: ClueCon
    inbound-timeout: 60
  ##呼叫命令
    call-command: originate
    call-gateway: callcenter-gw
    call-gateway-addr: 114.55.105.73:5060
  ##录音目录
    record-file-path: /home/hermes/record/
    record-prefix: http://172.16.140.71:808/
  ##单端口
    outbound-bd-port: 7800
    outbound-rcr-port: 7801
    outbound-tts-port: 7802


